### ISSUE TITLE
I want to create html text and save it to a variable and send it to template...but i can't

### ISSUE THREAD

**Issue by sadegh-shahbazi** [thedevsaddam/renderer#10]
I want to create html text 

for example: 

 `data1 := <h1>hello</h1>`

and save it to a variable->data1 and send it to template...but i can't

what can I do? noescape is removed from html/template

what should we do???

**Comment by sadegh-shahbazi** [comment]
sorry it was my fault..
I had a mistake

**Comment by thedevsaddam** [comment]
If you want to send HTML text to the template use `template.HTML(your html)` , please let me know is that the solution you asking for.

**Comment by sadegh-shahbazi** [comment]
It was my mistake

Sorry.

I ask the problem https://stackoverflow.com/questions/55657705/send-a-function-to-go-html-template-has-an-error-function-not-defined

and the answer is : Do not use relative imports

if I remove middelware my project works fine but now...It doesn't work...

Can you delete this issue?
