### ISSUE TITLE
FuncMap in Templates gives undefined error

### ISSUE THREAD

**Issue by chickson-va** [thedevsaddam/renderer#3]
Right now when I try to use a function in Templates, the FuncMap doesn't load before it tries to parse the template.

So as a result, I get an undefined error for the function I'm trying to use.

It looks like there was some work to do this in:
https://github.com/thedevsaddam/renderer/blob/master/renderer.go#L550-L555

Is this something that'll be finished :)?

Also thanks for your work on this!

**Comment by thedevsaddam** [comment]
FuncMap will work for `Template` method not for `HTML`

```go
func handler(w http.ResponseWriter, r *http.Request) {
	usr := struct {
		Name string
		Age  int
	}{"john doe", 30}

	tpls := []string{"template/layout.tmpl", "template/index.tmpl", "template/partial.tmpl"}
	rnd.FuncMap(template.FuncMap{
		"toUpper": toUpper,
	})
	err := rnd.Template(w, http.StatusOK, tpls, usr)
	if err != nil {
		log.Fatal(err) //respond with error page or message
	}
}
```

And for this particular case we can't have Funcmap in `HTML` method
